services:
  mongo:
    container_name: mongodb-health-qr
    image: mongo:4.4.25
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
