services:
  mongo:
    container_name: mongodb-health-qr
    image: mongo:4.4
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/my-health-profile
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
