import type { Metadata } from "next";
import "./globals.css";
import LayoutFrame from "./LayoutFrame";

export const metadata: Metadata = {
  title: "MediScanId",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="overflow-x-hidden">
      <body className="min-h-svh flex flex-col bg-gradient-to-br from-red-50 to-pink-50">
        <LayoutFrame>{children}</LayoutFrame>
      </body>
    </html>
  );
}
